development:
  adapter: postgresql
  encoding: unicode
  database: BillSplit_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: BillSplit_test
  pool: 5
  username:
